const http = require('http');
const { URL } = require('url');
const { randomUUID } = require('crypto');
const PORT = Number(process.env.CHROME_BRIDGE_PORT || 17373);
const HOST = process.env.CHROME_BRIDGE_HOST || '127.0.0.1';
const clients = new Map();
const results = new Map();
function now(){ return new Date().toISOString(); }
function getClient(clientId){ if(!clients.has(clientId)){ clients.set(clientId,{clientId,registeredAt:now(),lastSeen:now(),lastTab:null,queue:[]}); } return clients.get(clientId); }
function latestClient(){ return [...clients.values()].sort((a,b)=>Date.parse(b.lastSeen)-Date.parse(a.lastSeen))[0] || null; }
function sendJson(res, code, payload){ const body = JSON.stringify(payload, null, 2); res.writeHead(code, {'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}); res.end(body); }
function readBody(req){ return new Promise((resolve,reject)=>{ let raw=''; req.on('data',chunk=>raw+=chunk); req.on('end',()=>{ if(!raw) return resolve({}); try{ resolve(JSON.parse(raw)); } catch(error){ reject(error); } }); req.on('error',reject); }); }
function queueCommand(payload){ const targetClient = payload.clientId ? clients.get(payload.clientId) : latestClient(); if(!targetClient) throw new Error('No connected Chrome Bridge client found.'); const commandId = randomUUID(); const command = { commandId, action: payload.action, params: payload.params || {}, createdAt: now() }; results.set(commandId,{status:'pending',command,createdAt:now()}); targetClient.queue.push(command); return { commandId, clientId: targetClient.clientId }; }
async function waitForResult(commandId, timeoutMs){ const started = Date.now(); while(Date.now()-started<timeoutMs){ const entry = results.get(commandId); if(entry && entry.status !== 'pending') return entry; await new Promise(resolve=>setTimeout(resolve,150)); } return null; }
const server = http.createServer(async (req,res)=>{ try{ const url = new URL(req.url, `http://${req.headers.host}`); if(req.method==='OPTIONS') return sendJson(res,200,{ok:true}); if(req.method==='GET' && url.pathname==='/api/status'){ return sendJson(res,200,{ok:true,connectedClients:[...clients.values()].map(client=>({clientId:client.clientId,lastSeen:client.lastSeen,lastTab:client.lastTab})),latestClientId:latestClient()?.clientId || null,pendingResults:[...results.values()].filter(x=>x.status==='pending').length}); } if(req.method==='POST' && url.pathname==='/api/register'){ const body = await readBody(req); const client = getClient(body.clientId || randomUUID()); client.lastSeen = now(); if(body.lastTab) client.lastTab = body.lastTab; return sendJson(res,200,{ok:true,clientId:client.clientId,port:PORT}); } if(req.method==='GET' && url.pathname==='/api/pull'){ const clientId = url.searchParams.get('clientId'); if(!clientId) return sendJson(res,400,{ok:false,error:'clientId is required'}); const client = getClient(clientId); client.lastSeen = now(); const command = client.queue.shift() || null; return sendJson(res,200,{ok:true,command}); } if(req.method==='POST' && url.pathname==='/api/result'){ const body = await readBody(req); const client = getClient(body.clientId || 'unknown'); client.lastSeen = now(); if(body.lastTab) client.lastTab = body.lastTab; if(!body.commandId) return sendJson(res,400,{ok:false,error:'commandId is required'}); results.set(body.commandId,{status:body.ok===false?'error':'done',clientId:client.clientId,commandId:body.commandId,data:body.data || null,error:body.error || null,completedAt:now()}); return sendJson(res,200,{ok:true}); } if(req.method==='GET' && url.pathname==='/api/result'){ const commandId = url.searchParams.get('commandId'); const entry = commandId ? results.get(commandId) : null; if(!entry) return sendJson(res,404,{ok:false,error:'Unknown commandId'}); return sendJson(res,200,{ok:true,result:entry}); } if(req.method==='POST' && url.pathname==='/api/command'){ const body = await readBody(req); if(!body.action) return sendJson(res,400,{ok:false,error:'action is required'}); const queued = queueCommand(body); const waitMs = Number(body.waitMs || 15000); const result = await waitForResult(queued.commandId, waitMs); if(!result) return sendJson(res,202,{ok:true,pending:true,...queued}); return sendJson(res, result.status === 'error' ? 500 : 200, {ok:result.status !== 'error', ...queued, result}); } return sendJson(res,404,{ok:false,error:'Not found'}); } catch(error){ return sendJson(res,500,{ok:false,error:error.message || String(error)}); } });
server.listen(PORT, HOST, ()=>console.log(`Chrome Bridge hub listening on http://${HOST}:${PORT}`));